###POST ESTUDIANTE
POST http://localhost:5001/estudiante
Content-Type: application/json

{
    "id_estudiante": "12345678",
    "carrera": "Ingeniería de Sistemas",
    "semestre": 9,
    "usuario": {
    "nombre": "Juan Peralta",
    "correo": "jperalta@unicesar.edu.co",
    "contraseña": "hola1234"
    }
}

###POST DOCENTE

POST http://localhost:5001/docente
Content-Type: application/json

{
    "id_docente": "1234564490",
    "profesion": "Docente",
    "disponibilidad": "DISPONIBLE",
    "usuario": {
    "nombre": "Pablo Guerra",
    "correo": "pablo@unicesar.edu.co",
    "contraseña": "hola123"
    }

}