###POST ESTUDIANTE
POST http://localhost:5001/estudiante
Content-Type: application/json

{
    "id_estudiante": "012345678",
    "carrera": "Ingeniería de Sistemas",
    "semestre": 5,
    "usuario": {
    "nombre": "Laura Victoria Altahona",
    "correo": "lau@unicesar.edu.co",
    "contraseña": "hola1234"
    }
}

###POST DOCENTE
POST http://localhost:5001/docente
Content-Type: application/json

{
    "id_docente": "456987231",
    "profesion": "Docente",
    "disponibilidad": "DISPONIBLE",
    "carrera": "Ingenieria de sistemas",
    "usuario": {
    "nombre": "Pablo Sanchez",
    "correo": "pablo@unicesar.edu.co",
    "contraseña": "hola1234"
    }

}

### POST LOGIN
POST http://localhost:5001/usuario/login
Content-Type: application/json

{
  "correo": "cami@unicesar.edu.co",
  "contraseña": "hola1234"
}

### GET
GET http://localhost:5001/proyectos/asignados/2

###GET ENTREGAS ASIGNADAS
GET http://localhost:5001/entrega/asignadas/1


###GET PLANES DE ENTREGA POR PROYECTO
GET http://localhost:5001/entrega/proyecto/1

###GET ENTREGA POR PLAN
GET http://localhost:5001/entrega/entrega-por-plan/1

###GET MI PROYECTO
GET http://localhost:5001/proyectos/1

### GET FECHAS LIMITES
GET http://localhost:5001/entrega/fechas/5

### PATCH RETRO
PATCH http://localhost:5001/entrega/1/retroalimentacion
Content-Type: application/json

{
  "retroalimentacion": "cambiar objetivos",
  "ruta_retroalimentacion": "'/files/proyectodeinvestigacian.pdf'"
}

###PROYECTOS SIN DOCENTE
GET http://localhost:5001/proyectos/sin-docente

###DOCENTE DISPONIBLES
GET http://localhost:5001/docente/docentes-disponibles