###POST ESTUDIANTE
POST http://localhost:5001/estudiante
Content-Type: application/json

{
    "id_estudiante": "258963147",
    "carrera": "Ingeniería de Sistemas",
    "semestre": 10,
    "usuario": {
    "nombre": " Victoria ",
    "correo": "nlaurra@unicesar.edu.co",
    "contraseña": "hola1234"
    }
}
###GET ESTUDIANTE
GET http://localhost:5001/docente/getAll

### GET BY ID
GET http://localhost:5001/estudiante/id=/01235678

###delete
DELETE http://localhost:5001/estudiante/eliminar/258963147

###POST DOCENTE
POST http://localhost:5001/docente
Content-Type: application/json

{
    "id_docente": "123456789",
    "profesion": "Docente",
    "carrera": "Ingenieria de sistemas",
    "usuario": {
    "nombre": "Roberto Fernandez",
    "correo": "roberto@unicesar.edu.co",
    "contraseña": "hola1234"
    }
}

###POST JURADO
POST http://localhost:5001/jurado
Content-Type: application/json

{
    "idJurado": "123456789",
    "carrera": "Ingenieria de sistemas",
    "usuario": {
    "nombre": "Kadir Daza",
    "correo": "kadir@unicesar.edu.co",
    "contraseña": "hola1234"
    }
}

###PROYECTOS SIN JURADO
GET http://localhost:5001/proyectos/sin-jurado

### GET ALL JURADO
GET http://localhost:5001/jurado/getAll

### POST LOGIN
POST http://localhost:5001/usuario/login
Content-Type: application/json

{
  "correo": "kadir@unicesar.edu.co",
  "contraseña": "hola1234"
}

### GET
GET http://localhost:5001/proyectos/asignados/2

###GET ENTREGAS ASIGNADAS
GET http://localhost:5001/entrega/asignadas/1

###PROYECTOS ASIGNADOS
GET http://localhost:5001/proyectos/asignados/jurado/9
###GET PLANES DE ENTREGA POR PROYECTO
GET http://localhost:5001/entrega/proyecto/1

###GET ENTREGA POR PLAN
GET http://localhost:5001/entrega/entrega-por-plan/1

###GET MI PROYECTO
GET http://localhost:5001/proyectos/obtener/1

### GET FECHAS LIMITES
GET http://localhost:5001/entrega/fechas/5

### GET PROYECTOS POR TIPO
GET http://localhost:5001/proyectos/mostrarProyectos?tipo=Pasantía


### PATCH RETRO
PATCH http://localhost:5001/proyectos/cambiar-estado
Content-Type: application/json

{
  "idProyecto": "2",
  "estado": "APROBADO POR DOCENTE"
}

###PROYECTOS SIN DOCENTE
GET http://localhost:5001/proyectos/sin-docente

###DOCENTE DISPONIBLES
GET http://localhost:5001/docente/docentes-disponibles

###Registrar proyecto title, tipo, rutaDocumento, idEstudiante
POST http://localhost:5001/proyectos
Content-Type: application/json

{
  "title": "Sistema de verificacion de identidad",
  "tipo": "Proyecto de grado",
  "rutaDocumento": "/files/proyectodeinvestigacian.pdf",
  "idEstudiante": "98765432"
}